### ISSUE TITLE
/auth/token route returns "bearer" instead of "Bearer"

### ISSUE THREAD

**Issue by tonsmets** [OpenLEADR/openleadr-rs#91]
When requesting an auth_token the response gives the wrong `token_type` so it breaks any generated code based on the OpenAPI spec. 

```
    clientCredentialResponse:
      type: object
      description: |
        Body response from /auth/token. Note snake case per https://www.rfc-editor.org/rfc/rfc6749
      required:
        - access_token
        - token_type
      properties:
        token_type:
          type: string
          description: token type, must be Bearer.
          example: Bearer
          enum: [Bearer]
```

Should be an easy fix by just uppercasing the first letter so `bearer` becomes `Bearer`.

https://github.com/OpenLEADR/openleadr-rs/blob/83097d4a281f84003abb6d1bac273bb993d1d3b9/openleadr-vtn/src/api/auth.rs#L147
